// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class2 {
        public const int ITEM_CLASS2_WEAPON02_MAX = 17;
        public struct ITEM_CLASS2_WEAPON02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_WEAPON02[] stItem_CLASS2_Weapon02 = new ITEM_CLASS2_WEAPON02[ITEM_CLASS2_WEAPON02_MAX] {
            new ITEM_CLASS2_WEAPON02 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë¸®º¼¹ö",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 700,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 1,
                NAME_KOR = "Ã»µ¿¸®º¼¹ö",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 2200,
                DURABILITY = 19,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 2,
                NAME_KOR = "Ã»µ¿¼¦°Ç",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 6350,
                DURABILITY = 27,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 95,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 3,
                NAME_KOR = "Ã»µ¿ÇÚµå°Ç",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 13000,
                DURABILITY = 35,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 140,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 4,
                NAME_KOR = "°­Ã¶¸®º¼¹ö",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 22200,
                DURABILITY = 44,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 185,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 5,
                NAME_KOR = "°­Ã¶¼¦°Ç",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 33850,
                DURABILITY = 52,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 230,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 6,
                NAME_KOR = "°­Ã¶ÇÚµå°Ç",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 48000,
                DURABILITY = 60,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 275,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 7,
                NAME_KOR = "ÇÕ±Ý¸®º¼¹ö",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 64650,
                DURABILITY = 68,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 320,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 8,
                NAME_KOR = "ÇÕ±Ý¼¦°Ç",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 83800,
                DURABILITY = 76,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 365,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 9,
                NAME_KOR = "ÇÕ±ÝÇÚµå°Ç",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 105450,
                DURABILITY = 84,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 410,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 10,
                NAME_KOR = "ÇÕ±Ý¸®º¼¹ö",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 129600,
                DURABILITY = 92,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 455,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 11,
                NAME_KOR = "¿À¸®ÄÜ¼¦°Ç",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 156250,
                DURABILITY = 100,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 500,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 12,
                NAME_KOR = "¿À¸®ÄÜÇÚµå°Ç",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 185450,
                DURABILITY = 109,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 545,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 13,
                NAME_KOR = "Ã»µ¿Ä³³í",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 13350,
                DURABILITY = 42,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 196,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 14,
                NAME_KOR = "°­Ã¶Ä³³í",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 48700,
                DURABILITY = 74,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 385,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 15,
                NAME_KOR = "ÇÕ±ÝÄ³³í",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 106500,
                DURABILITY = 105,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 574,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 16,
                NAME_KOR = "¿À¸®ÄÜÄ³³í",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 186800,
                DURABILITY = 136,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 763,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_HELMET02_MAX = 17;
        public struct ITEM_CLASS2_HELMET02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_HELMET02[] stItem_CLASS2_Helmet02 = new ITEM_CLASS2_HELMET02[ITEM_CLASS2_HELMET02_MAX] {
            new ITEM_CLASS2_HELMET02 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë»ö¾È°æ",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 800,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 1,
                NAME_KOR = "³°Àº¼±±×¶ó½º",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 2500,
                DURABILITY = 14,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 2,
                NAME_KOR = "³°ÀºÇï¸ä",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 6900,
                DURABILITY = 17,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 12,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 3,
                NAME_KOR = "³°Àº°í±Û",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 13850,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý¼±±×¶ó½º",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 23250,
                DURABILITY = 24,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 22,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÇï¸ä",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 35150,
                DURABILITY = 27,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý°í±Û",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 49550,
                DURABILITY = 30,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 7,
                NAME_KOR = "°í±Þ¼±±×¶ó½º",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 66450,
                DURABILITY = 33,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 37,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 8,
                NAME_KOR = "°í±ÞÇï¸ä",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 85850,
                DURABILITY = 36,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 42,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 9,
                NAME_KOR = "°í±Þ°í±Û",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 107750,
                DURABILITY = 39,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 10,
                NAME_KOR = "°í±Þ¼±±×¶ó½º",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 132150,
                DURABILITY = 42,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÇï¸ä",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 159100,
                DURABILITY = 46,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 57,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 12,
                NAME_KOR = "Èñ±Í°í±Û",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 182400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 13,
                NAME_KOR = "³°Àº»ÔÅõ±¸",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 13850,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý»ÔÅõ±¸",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 49600,
                DURABILITY = 31,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 15,
                NAME_KOR = "°í±Þ»ÔÅõ±¸",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 107900,
                DURABILITY = 42,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 65,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 16,
                NAME_KOR = "Èñ±Í»ÔÅõ±¸",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_ARMOR02_MAX = 17;
        public struct ITEM_CLASS2_ARMOR02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_ARMOR02[] stItem_CLASS2_Armor02 = new ITEM_CLASS2_ARMOR02[ITEM_CLASS2_ARMOR02_MAX] {
            new ITEM_CLASS2_ARMOR02 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÅÎ½Ãµµ",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 1100,
                DURABILITY = 13,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 1,
                NAME_KOR = "³°ÀºÅÎ½Ãµµ",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 3200,
                DURABILITY = 15,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 2,
                NAME_KOR = "³°ÀºÀçÅ¶",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 8150,
                DURABILITY = 19,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 3,
                NAME_KOR = "³°Àº·ÕÄÚÆ®",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 15550,
                DURABILITY = 22,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÅÎ½Ãµµ",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 25450,
                DURABILITY = 25,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÀçÅ¶",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 37900,
                DURABILITY = 29,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý·ÕÄÚÆ®",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 52800,
                DURABILITY = 32,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 45,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 7,
                NAME_KOR = "°í±ÞÅÎ½Ãµµ",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 70200,
                DURABILITY = 35,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 8,
                NAME_KOR = "°í±ÞÀçÅ¶",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 90250,
                DURABILITY = 39,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 59,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 9,
                NAME_KOR = "°í±Þ·ÕÄÚÆ®",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 112550,
                DURABILITY = 42,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 66,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÅÎ½Ãµµ",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 137500,
                DURABILITY = 46,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 73,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÀçÅ¶",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 164900,
                DURABILITY = 49,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 80,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 12,
                NAME_KOR = "Èñ±Í·ÕÄÚÆ®",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 13,
                NAME_KOR = "³°Àº½´Æ®",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 15600,
                DURABILITY = 23,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý½´Æ®",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 52900,
                DURABILITY = 34,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 64,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 15,
                NAME_KOR = "°í±Þ½´Æ®",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 112750,
                DURABILITY = 46,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 93,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 16,
                NAME_KOR = "Èñ±Í½´Æ®",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 182750,
                DURABILITY = 55,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 119,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_GLOVES02_MAX = 17;
        public struct ITEM_CLASS2_GLOVES02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_GLOVES02[] stItem_CLASS2_Gloves02 = new ITEM_CLASS2_GLOVES02[ITEM_CLASS2_GLOVES02_MAX] {
            new ITEM_CLASS2_GLOVES02 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÇÚµå",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 1450,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 4,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 1,
                NAME_KOR = "³°ÀºÇÚµå",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 3950,
                DURABILITY = 15,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 2,
                NAME_KOR = "³°Àº°¡Á×ÇÚµå",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 9350,
                DURABILITY = 18,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 3,
                NAME_KOR = "³°Àº½ÇÅ©ÇÚµå",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 17250,
                DURABILITY = 21,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÇÚµå",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 27650,
                DURABILITY = 24,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý°¡Á×ÇÚµå",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 40550,
                DURABILITY = 27,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý½ÇÅ©ÇÚµå",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 55950,
                DURABILITY = 30,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 7,
                NAME_KOR = "°í±ÞÇÚµå",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 73850,
                DURABILITY = 33,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 8,
                NAME_KOR = "°í±Þ°¡Á×ÇÚµå",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 94250,
                DURABILITY = 36,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 9,
                NAME_KOR = "°í±Þ½ÇÅ©ÇÚµå",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 117150,
                DURABILITY = 39,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 39,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÇÚµå",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 142550,
                DURABILITY = 42,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 43,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 11,
                NAME_KOR = "Èñ±Í°¡Á×ÇÚµå",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 170450,
                DURABILITY = 45,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 12,
                NAME_KOR = "Èñ±Í½ÇÅ©ÇÚµå",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 182350,
                DURABILITY = 47,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 13,
                NAME_KOR = "³°Àº°ÇÇÚµå",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 17300,
                DURABILITY = 22,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý°ÇÇÚµå",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 56050,
                DURABILITY = 32,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 15,
                NAME_KOR = "°í±Þ°ÇÇÚµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 117250,
                DURABILITY = 41,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 16,
                NAME_KOR = "Èñ±Í°ÇÇÚµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 182450,
                DURABILITY = 49,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 68,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_SHOES02_MAX = 17;
        public struct ITEM_CLASS2_SHOES02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_SHOES02[] stItem_CLASS2_Shoes02 = new ITEM_CLASS2_SHOES02[ITEM_CLASS2_SHOES02_MAX] {
            new ITEM_CLASS2_SHOES02 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÈú",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 1950,
                DURABILITY = 14,
                LIMIT_LEVEL = 5,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 1,
                NAME_KOR = "³°ÀºÃ»Å°Èú",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 4850,
                DURABILITY = 16,
                LIMIT_LEVEL = 9,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 2,
                NAME_KOR = "³°ÀºÇÏÀÌÈú",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 10750,
                DURABILITY = 19,
                LIMIT_LEVEL = 14,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 3,
                NAME_KOR = "³°ÀºÀüÅõÈú",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 19150,
                DURABILITY = 22,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 20,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÃ»Å°Èú",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 30200,
                DURABILITY = 26,
                LIMIT_LEVEL = 24,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÇÏÀÌÈú",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 43500,
                DURABILITY = 29,
                LIMIT_LEVEL = 29,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÀüÅõÈú",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 59400,
                DURABILITY = 32,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 7,
                NAME_KOR = "°í±ÞÃ»Å°Èú",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 77800,
                DURABILITY = 35,
                LIMIT_LEVEL = 39,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 8,
                NAME_KOR = "°í±ÞÇÏÀÌÈú",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 98700,
                DURABILITY = 38,
                LIMIT_LEVEL = 44,
                EFFECT = 5,
                EFF_VALUE = 45,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 9,
                NAME_KOR = "°í±ÞÀüÅõÈú",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 122100,
                DURABILITY = 41,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÃ»Å°Èú",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 148000,
                DURABILITY = 44,
                LIMIT_LEVEL = 54,
                EFFECT = 5,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÇÏÀÌÈú",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 176400,
                DURABILITY = 47,
                LIMIT_LEVEL = 59,
                EFFECT = 5,
                EFF_VALUE = 60,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÀüÅõÈú",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 182400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 13,
                NAME_KOR = "³°ÀºÅ³Èú",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 19200,
                DURABILITY = 23,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹ÝÅ³Èú",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 59500,
                DURABILITY = 34,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 15,
                NAME_KOR = "°í±ÞÅ³Èú",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 122250,
                DURABILITY = 44,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 70,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 16,
                NAME_KOR = "Èñ±ÍÅ³Èú",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_AVATAR02_MAX = 3;
        public struct ITEM_CLASS2_AVATAR02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_AVATAR02[] stItem_CLASS2_Avatar02 = new ITEM_CLASS2_AVATAR02[ITEM_CLASS2_AVATAR02_MAX] {
            new ITEM_CLASS2_AVATAR02 {
                ICON = 0,
                NAME_KOR = "Åä³¢ ¾Æ¹ÙÅ¸",
                NAME_ENG = "Åä³¢ ¾Æ¹ÙÅ¸",
                NAME_JPN = "Åä³¢ ¾Æ¹ÙÅ¸",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_AVATAR02 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_AVATAR02 {
                ICON = 2,
                NAME_KOR = "DLC2",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}