// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class2 {
        public const int ITEM_CLASS2_WEAPON02_MAX = 17;
        public struct ITEM_CLASS2_WEAPON02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_WEAPON02[] stItem_CLASS2_Weapon02 = new ITEM_CLASS2_WEAPON02[ITEM_CLASS2_WEAPON02_MAX] {
            new ITEM_CLASS2_WEAPON02 {
                ICON = 0,
                NAME_KOR = "수련용리볼버",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 700,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 1,
                NAME_KOR = "청동리볼버",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 2200,
                DURABILITY = 19,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 2,
                NAME_KOR = "청동샷건",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 6350,
                DURABILITY = 27,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 95,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 3,
                NAME_KOR = "청동핸드건",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 13000,
                DURABILITY = 35,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 140,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 4,
                NAME_KOR = "강철리볼버",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 22200,
                DURABILITY = 44,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 185,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 5,
                NAME_KOR = "강철샷건",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 33850,
                DURABILITY = 52,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 230,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 6,
                NAME_KOR = "강철핸드건",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 48000,
                DURABILITY = 60,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 275,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 7,
                NAME_KOR = "합금리볼버",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 64650,
                DURABILITY = 68,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 320,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 8,
                NAME_KOR = "합금샷건",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名?の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 83800,
                DURABILITY = 76,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 365,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 9,
                NAME_KOR = "합금핸드건",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高?察?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 105450,
                DURABILITY = 84,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 410,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 10,
                NAME_KOR = "합금리볼버",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 129600,
                DURABILITY = 92,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 455,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 11,
                NAME_KOR = "오리콘샷건",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 156250,
                DURABILITY = 100,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 500,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 12,
                NAME_KOR = "오리콘핸드건",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 185450,
                DURABILITY = 109,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 545,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 13,
                NAME_KOR = "청동캐논",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖?アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 13350,
                DURABILITY = 42,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 196,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 14,
                NAME_KOR = "강철캐논",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 48700,
                DURABILITY = 74,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 385,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 15,
                NAME_KOR = "합금캐논",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 106500,
                DURABILITY = 105,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 574,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_WEAPON02 {
                ICON = 16,
                NAME_KOR = "오리콘캐논",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 1,
                PRICE = 186800,
                DURABILITY = 136,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 763,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_HELMET02_MAX = 17;
        public struct ITEM_CLASS2_HELMET02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_HELMET02[] stItem_CLASS2_Helmet02 = new ITEM_CLASS2_HELMET02[ITEM_CLASS2_HELMET02_MAX] {
            new ITEM_CLASS2_HELMET02 {
                ICON = 0,
                NAME_KOR = "수련용색안경",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 800,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 1,
                NAME_KOR = "낡은선그라스",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 2500,
                DURABILITY = 14,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 2,
                NAME_KOR = "낡은헬멧",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 6900,
                DURABILITY = 17,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 12,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 3,
                NAME_KOR = "낡은고글",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 13850,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 4,
                NAME_KOR = "일반선그라스",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 23250,
                DURABILITY = 24,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 22,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 5,
                NAME_KOR = "일반헬멧",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 35150,
                DURABILITY = 27,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 6,
                NAME_KOR = "일반고글",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 49550,
                DURABILITY = 30,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 7,
                NAME_KOR = "고급선그라스",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 66450,
                DURABILITY = 33,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 37,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 8,
                NAME_KOR = "고급헬멧",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名?の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 85850,
                DURABILITY = 36,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 42,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 9,
                NAME_KOR = "고급고글",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高?察?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 107750,
                DURABILITY = 39,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 10,
                NAME_KOR = "고급선그라스",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 132150,
                DURABILITY = 42,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 11,
                NAME_KOR = "희귀헬멧",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 159100,
                DURABILITY = 46,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 57,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 12,
                NAME_KOR = "희귀고글",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 182400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 13,
                NAME_KOR = "낡은뿔투구",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖?アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 13850,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 14,
                NAME_KOR = "일반뿔투구",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 49600,
                DURABILITY = 31,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 15,
                NAME_KOR = "고급뿔투구",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 107900,
                DURABILITY = 42,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 65,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_HELMET02 {
                ICON = 16,
                NAME_KOR = "희귀뿔투구",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_ARMOR02_MAX = 17;
        public struct ITEM_CLASS2_ARMOR02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_ARMOR02[] stItem_CLASS2_Armor02 = new ITEM_CLASS2_ARMOR02[ITEM_CLASS2_ARMOR02_MAX] {
            new ITEM_CLASS2_ARMOR02 {
                ICON = 0,
                NAME_KOR = "수련용턱시도",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 1100,
                DURABILITY = 13,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 1,
                NAME_KOR = "낡은턱시도",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 3200,
                DURABILITY = 15,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 2,
                NAME_KOR = "낡은재킷",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 8150,
                DURABILITY = 19,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 3,
                NAME_KOR = "낡은롱코트",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 15550,
                DURABILITY = 22,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 4,
                NAME_KOR = "일반턱시도",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 25450,
                DURABILITY = 25,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 5,
                NAME_KOR = "일반재킷",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 37900,
                DURABILITY = 29,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 6,
                NAME_KOR = "일반롱코트",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 52800,
                DURABILITY = 32,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 45,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 7,
                NAME_KOR = "고급턱시도",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 70200,
                DURABILITY = 35,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 8,
                NAME_KOR = "고급재킷",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名?の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 90250,
                DURABILITY = 39,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 59,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 9,
                NAME_KOR = "고급롱코트",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高?察?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 112550,
                DURABILITY = 42,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 66,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 10,
                NAME_KOR = "희귀턱시도",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 137500,
                DURABILITY = 46,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 73,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 11,
                NAME_KOR = "희귀재킷",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 164900,
                DURABILITY = 49,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 80,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 12,
                NAME_KOR = "희귀롱코트",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 13,
                NAME_KOR = "낡은슈트",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖?アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 15600,
                DURABILITY = 23,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 14,
                NAME_KOR = "일반슈트",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 52900,
                DURABILITY = 34,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 64,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 15,
                NAME_KOR = "고급슈트",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 112750,
                DURABILITY = 46,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 93,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_ARMOR02 {
                ICON = 16,
                NAME_KOR = "희귀슈트",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 1,
                PRICE = 182750,
                DURABILITY = 55,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 119,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_GLOVES02_MAX = 17;
        public struct ITEM_CLASS2_GLOVES02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_GLOVES02[] stItem_CLASS2_Gloves02 = new ITEM_CLASS2_GLOVES02[ITEM_CLASS2_GLOVES02_MAX] {
            new ITEM_CLASS2_GLOVES02 {
                ICON = 0,
                NAME_KOR = "수련용핸드",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 1450,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 4,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 1,
                NAME_KOR = "낡은핸드",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 3950,
                DURABILITY = 15,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 2,
                NAME_KOR = "낡은가죽핸드",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 9350,
                DURABILITY = 18,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 3,
                NAME_KOR = "낡은실크핸드",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 17250,
                DURABILITY = 21,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 4,
                NAME_KOR = "일반핸드",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 27650,
                DURABILITY = 24,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 5,
                NAME_KOR = "일반가죽핸드",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 40550,
                DURABILITY = 27,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 6,
                NAME_KOR = "일반실크핸드",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 55950,
                DURABILITY = 30,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 7,
                NAME_KOR = "고급핸드",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 73850,
                DURABILITY = 33,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 8,
                NAME_KOR = "고급가죽핸드",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名?の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 94250,
                DURABILITY = 36,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 9,
                NAME_KOR = "고급실크핸드",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高?察?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 117150,
                DURABILITY = 39,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 39,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 10,
                NAME_KOR = "희귀핸드",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 142550,
                DURABILITY = 42,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 43,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 11,
                NAME_KOR = "희귀가죽핸드",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 170450,
                DURABILITY = 45,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 12,
                NAME_KOR = "희귀실크핸드",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 182350,
                DURABILITY = 47,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 13,
                NAME_KOR = "낡은건핸드",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖?アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 17300,
                DURABILITY = 22,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 14,
                NAME_KOR = "일반건핸드",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 56050,
                DURABILITY = 32,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 15,
                NAME_KOR = "고급건핸드",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 117250,
                DURABILITY = 41,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_GLOVES02 {
                ICON = 16,
                NAME_KOR = "희귀건핸드",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 1,
                PRICE = 182450,
                DURABILITY = 49,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 68,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_SHOES02_MAX = 17;
        public struct ITEM_CLASS2_SHOES02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_SHOES02[] stItem_CLASS2_Shoes02 = new ITEM_CLASS2_SHOES02[ITEM_CLASS2_SHOES02_MAX] {
            new ITEM_CLASS2_SHOES02 {
                ICON = 0,
                NAME_KOR = "수련용힐",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 1950,
                DURABILITY = 14,
                LIMIT_LEVEL = 5,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 1,
                NAME_KOR = "낡은청키힐",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 4850,
                DURABILITY = 16,
                LIMIT_LEVEL = 9,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 2,
                NAME_KOR = "낡은하이힐",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 10750,
                DURABILITY = 19,
                LIMIT_LEVEL = 14,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 3,
                NAME_KOR = "낡은전투힐",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 19150,
                DURABILITY = 22,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 20,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 4,
                NAME_KOR = "일반청키힐",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 30200,
                DURABILITY = 26,
                LIMIT_LEVEL = 24,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 5,
                NAME_KOR = "일반하이힐",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 43500,
                DURABILITY = 29,
                LIMIT_LEVEL = 29,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 6,
                NAME_KOR = "일반전투힐",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 59400,
                DURABILITY = 32,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 7,
                NAME_KOR = "고급청키힐",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 77800,
                DURABILITY = 35,
                LIMIT_LEVEL = 39,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 8,
                NAME_KOR = "고급하이힐",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名?の?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 98700,
                DURABILITY = 38,
                LIMIT_LEVEL = 44,
                EFFECT = 5,
                EFF_VALUE = 45,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 9,
                NAME_KOR = "고급전투힐",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高?察?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 122100,
                DURABILITY = 41,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 10,
                NAME_KOR = "희귀청키힐",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレ?トソ?ド",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 148000,
                DURABILITY = 44,
                LIMIT_LEVEL = 54,
                EFFECT = 5,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 11,
                NAME_KOR = "희귀하이힐",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 176400,
                DURABILITY = 47,
                LIMIT_LEVEL = 59,
                EFFECT = 5,
                EFF_VALUE = 60,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 12,
                NAME_KOR = "희귀전투힐",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 182400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 13,
                NAME_KOR = "낡은킬힐",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖?アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 19200,
                DURABILITY = 23,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 14,
                NAME_KOR = "일반킬힐",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 59500,
                DURABILITY = 34,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 15,
                NAME_KOR = "고급킬힐",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 122250,
                DURABILITY = 44,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 70,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_SHOES02 {
                ICON = 16,
                NAME_KOR = "희귀킬힐",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の?手?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 1,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS2_AVATAR02_MAX = 3;
        public struct ITEM_CLASS2_AVATAR02 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS2_AVATAR02[] stItem_CLASS2_Avatar02 = new ITEM_CLASS2_AVATAR02[ITEM_CLASS2_AVATAR02_MAX] {
            new ITEM_CLASS2_AVATAR02 {
                ICON = 0,
                NAME_KOR = "토끼 아바타",
                NAME_ENG = "Rabbit Avatar",
                NAME_JPN = "토끼 아바타",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_AVATAR02 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS2_AVATAR02 {
                ICON = 2,
                NAME_KOR = "DLC2",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 1,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}
