// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class4 {
        public const int ITEM_CLASS4_WEAPON04_MAX = 17;
        public struct ITEM_CLASS4_WEAPON04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_WEAPON04[] stItem_CLASS4_Weapon04 = new ITEM_CLASS4_WEAPON04[ITEM_CLASS4_WEAPON04_MAX] {
            new ITEM_CLASS4_WEAPON04 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë¾Ï·¿",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 655,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 1,
                NAME_KOR = "Ã»µ¿¾Ï·¿",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 1125,
                DURABILITY = 20,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 60,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 2,
                NAME_KOR = "Ã»µ¿¸Ó½Å¾Ï",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 2000,
                DURABILITY = 30,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 115,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 3,
                NAME_KOR = "Ã»µ¿¹èÆ²¾Ï",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 3075,
                DURABILITY = 39,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 170,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 4,
                NAME_KOR = "°­Ã¶¾Ï·¿",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 4450,
                DURABILITY = 49,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 225,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 5,
                NAME_KOR = "°­Ã¶¸Ó½Å¾Ï",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 6025,
                DURABILITY = 58,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 280,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 6,
                NAME_KOR = "°­Ã¶¹èÆ²¾Ï",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 7850,
                DURABILITY = 67,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 335,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 7,
                NAME_KOR = "ÇÕ±Ý¾Ï·¿",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 9975,
                DURABILITY = 77,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 390,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 8,
                NAME_KOR = "ÇÕ±Ý¸Ó½Å¾Ï",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 12300,
                DURABILITY = 86,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 445,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 9,
                NAME_KOR = "ÇÕ±Ý¹èÆ²¾Ï",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 14875,
                DURABILITY = 95,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 500,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 10,
                NAME_KOR = "¿À¸®ÄÜ¾Ï·¿",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 17750,
                DURABILITY = 105,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 555,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 11,
                NAME_KOR = "¿À¸®ÄÜ¸Ó½Å¾Ï",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 20825,
                DURABILITY = 114,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 610,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 12,
                NAME_KOR = "¿À¸®ÄÜ¹èÆ²¾Ï",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 24200,
                DURABILITY = 124,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 665,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 13,
                NAME_KOR = "Ã»µ¿ÆÄ¿ö¾Ï",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 3525,
                DURABILITY = 48,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 238,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 14,
                NAME_KOR = "°­Ã¶ÆÄ¿ö¾Ï",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 8700,
                DURABILITY = 84,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 469,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 15,
                NAME_KOR = "ÇÕ±ÝÆÄ¿ö¾Ï",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 16125,
                DURABILITY = 120,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 700,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_WEAPON04 {
                ICON = 16,
                NAME_KOR = "¿À¸®ÄÜÆÄ¿ö¾Ï",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 3,
                PRICE = 25850,
                DURABILITY = 157,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 931,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS4_HELMET04_MAX = 17;
        public struct ITEM_CLASS4_HELMET04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_HELMET04[] stItem_CLASS4_Helmet04 = new ITEM_CLASS4_HELMET04[ITEM_CLASS4_HELMET04_MAX] {
            new ITEM_CLASS4_HELMET04 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÆäµµ¶ó",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 620,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 1,
                NAME_KOR = "³°ÀºÆäµµ¶ó",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 880,
                DURABILITY = 14,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 2,
                NAME_KOR = "³°Àº¸¶¹ý¸ð",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 1455,
                DURABILITY = 17,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 3,
                NAME_KOR = "³°ÀºÇÐÀÚ¸ð",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 2280,
                DURABILITY = 20,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÆäµµ¶ó",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 3305,
                DURABILITY = 22,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 12,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý¸¶¹ý¸ð",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 4630,
                DURABILITY = 25,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÇÐÀÚ¸ð",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 6205,
                DURABILITY = 28,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 7,
                NAME_KOR = "°í±ÞÆäµµ¶ó",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 8030,
                DURABILITY = 31,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 20,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 8,
                NAME_KOR = "°í±Þ¸¶¹ý¸ð",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 10405,
                DURABILITY = 34,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 9,
                NAME_KOR = "°í±ÞÇÐÀÚ¸ð",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 12430,
                DURABILITY = 37,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÆäµµ¶ó",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 14955,
                DURABILITY = 39,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 11,
                NAME_KOR = "Èñ±Í¸¶¹ý¸ð",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 17780,
                DURABILITY = 42,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÇÐÀÚ¸ð",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 13,
                NAME_KOR = "³°ÀºÈÄµå",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 2280,
                DURABILITY = 20,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹ÝÈÄµå",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 6255,
                DURABILITY = 29,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 15,
                NAME_KOR = "°í±ÞÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 12480,
                DURABILITY = 38,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 36,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_HELMET04 {
                ICON = 16,
                NAME_KOR = "Èñ±ÍÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 3,
                PRICE = 20300,
                DURABILITY = 46,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS4_ARMOR04_MAX = 17;
        public struct ITEM_CLASS4_ARMOR04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_ARMOR04[] stItem_CLASS4_Armor04 = new ITEM_CLASS4_ARMOR04[ITEM_CLASS4_ARMOR04_MAX] {
            new ITEM_CLASS4_ARMOR04 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÀÇº¹",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 645,
                DURABILITY = 12,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 1,
                NAME_KOR = "³°ÀºÀÇº¹",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 995,
                DURABILITY = 15,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 2,
                NAME_KOR = "³°Àº¸¶¹ýº¹",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 1570,
                DURABILITY = 17,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 8,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 3,
                NAME_KOR = "³°ÀºÁ¦»çº¹",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 2445,
                DURABILITY = 20,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÀÇº¹",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 3570,
                DURABILITY = 23,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý¸¶¹ýº¹",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 4945,
                DURABILITY = 26,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 18,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÁ¦»çº¹",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 6570,
                DURABILITY = 29,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 7,
                NAME_KOR = "°í±ÞÀÇº¹",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 8445,
                DURABILITY = 32,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 8,
                NAME_KOR = "°í±Þ¸¶¹ýº¹",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 10570,
                DURABILITY = 35,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 9,
                NAME_KOR = "°í±ÞÁ¦»çº¹",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 12945,
                DURABILITY = 38,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÀÇº¹",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 15569,
                DURABILITY = 41,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 11,
                NAME_KOR = "Èñ±Í¸¶¹ýº¹",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 18445,
                DURABILITY = 44,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÁ¦»çº¹",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 13,
                NAME_KOR = "³°ÀºÈÄµå",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 2495,
                DURABILITY = 21,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹ÝÈÄµå",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 6620,
                DURABILITY = 30,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 15,
                NAME_KOR = "°í±ÞÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 12995,
                DURABILITY = 39,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_ARMOR04 {
                ICON = 16,
                NAME_KOR = "Èñ±ÍÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 3,
                PRICE = 20350,
                DURABILITY = 47,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 56,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS4_GLOVES04_MAX = 17;
        public struct ITEM_CLASS4_GLOVES04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_GLOVES04[] stItem_CLASS4_Gloves04 = new ITEM_CLASS4_GLOVES04[ITEM_CLASS4_GLOVES04_MAX] {
            new ITEM_CLASS4_GLOVES04 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë¼ö°©",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 730,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 1,
                NAME_KOR = "³°Àº¼ö°©",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 1070,
                DURABILITY = 15,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 4,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 2,
                NAME_KOR = "³°Àººñ´Ü¼ö°©",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 1745,
                DURABILITY = 18,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 3,
                NAME_KOR = "³°Àº¸¶·Â¼ö°©",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 2620,
                DURABILITY = 20,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 8,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý¼ö°©",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 3795,
                DURABILITY = 23,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ýºñ´Ü¼ö°©",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 5220,
                DURABILITY = 26,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý¸¶·Â¼ö°©",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 6895,
                DURABILITY = 29,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 7,
                NAME_KOR = "°í±Þ¼ö°©",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 8820,
                DURABILITY = 32,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 8,
                NAME_KOR = "°í±Þºñ´Ü¼ö°©",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 10945,
                DURABILITY = 34,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 9,
                NAME_KOR = "°í±Þ¸¶·Â¼ö°©",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 13370,
                DURABILITY = 37,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 10,
                NAME_KOR = "Èñ±Í¼ö°©",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 16044,
                DURABILITY = 40,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 11,
                NAME_KOR = "Èñ±Íºñ´Ü¼ö°©",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 18970,
                DURABILITY = 43,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 12,
                NAME_KOR = "Èñ±Í¸¶·Â¼ö°©",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 20200,
                DURABILITY = 44,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 13,
                NAME_KOR = "³°ÀºÈÄµå",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 2670,
                DURABILITY = 21,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹ÝÈÄµå",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 6945,
                DURABILITY = 30,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 15,
                NAME_KOR = "°í±ÞÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 13420,
                DURABILITY = 38,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_GLOVES04 {
                ICON = 16,
                NAME_KOR = "Èñ±ÍÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 3,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS4_SHOES04_MAX = 17;
        public struct ITEM_CLASS4_SHOES04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_SHOES04[] stItem_CLASS4_Shoes04 = new ITEM_CLASS4_SHOES04[ITEM_CLASS4_SHOES04_MAX] {
            new ITEM_CLASS4_SHOES04 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë½´Áî",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 775,
                DURABILITY = 13,
                LIMIT_LEVEL = 5,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 1,
                NAME_KOR = "³°Àº½´Áî",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 1205,
                DURABILITY = 16,
                LIMIT_LEVEL = 9,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 2,
                NAME_KOR = "³°ÀººÎÃ÷",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 1880,
                DURABILITY = 18,
                LIMIT_LEVEL = 14,
                EFFECT = 5,
                EFF_VALUE = 8,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 3,
                NAME_KOR = "³°ÀºÀåÈ­",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 2855,
                DURABILITY = 21,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý½´Áî",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 4080,
                DURABILITY = 24,
                LIMIT_LEVEL = 24,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝºÎÃ÷",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 5555,
                DURABILITY = 27,
                LIMIT_LEVEL = 29,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÀåÈ­",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 7280,
                DURABILITY = 30,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 7,
                NAME_KOR = "°í±Þ½´Áî",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 9255,
                DURABILITY = 33,
                LIMIT_LEVEL = 39,
                EFFECT = 5,
                EFF_VALUE = 22,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 8,
                NAME_KOR = "°í±ÞºÎÃ÷",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 11480,
                DURABILITY = 36,
                LIMIT_LEVEL = 44,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 9,
                NAME_KOR = "°í±ÞÀåÈ­",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 13905,
                DURABILITY = 38,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 10,
                NAME_KOR = "Èñ±Í½´Áî",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 16630,
                DURABILITY = 41,
                LIMIT_LEVEL = 54,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍºÎÃ÷",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 19605,
                DURABILITY = 44,
                LIMIT_LEVEL = 59,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÀåÈ­",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 13,
                NAME_KOR = "³°ÀºÈÄµå",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 2905,
                DURABILITY = 22,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹ÝÈÄµå",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 7330,
                DURABILITY = 31,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 15,
                NAME_KOR = "°í±ÞÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 14005,
                DURABILITY = 40,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_SHOES04 {
                ICON = 16,
                NAME_KOR = "Èñ±ÍÈÄµå",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 3,
                PRICE = 20300,
                DURABILITY = 46,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS4_AVATAR04_MAX = 3;
        public struct ITEM_CLASS4_AVATAR04 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS4_AVATAR04[] stItem_CLASS4_Avatar04 = new ITEM_CLASS4_AVATAR04[ITEM_CLASS4_AVATAR04_MAX] {
            new ITEM_CLASS4_AVATAR04 {
                ICON = 0,
                NAME_KOR = "°ø·æ ¾Æ¹ÙÅ¸",
                NAME_ENG = "°ø·æ ¾Æ¹ÙÅ¸",
                NAME_JPN = "°ø·æ ¾Æ¹ÙÅ¸",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_AVATAR04 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS4_AVATAR04 {
                ICON = 2,
                NAME_KOR = "DLC2",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}
