// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class5 {
        public const int ITEM_CLASS5_WEAPON05_MAX = 17;
        public struct ITEM_CLASS5_WEAPON05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        
        }
        public static ITEM_CLASS5_WEAPON05[] stItem_CLASS5_Weapon05 = new ITEM_CLASS5_WEAPON05[ITEM_CLASS5_WEAPON05_MAX] {
            new ITEM_CLASS5_WEAPON05 {
                ICON = 0,
                NAME_KOR = "수련용사슬낫",
                NAME_ENG = "Apprentice Chain Scythe",
                NAME_JPN = "封印された大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 655,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 1,
                NAME_KOR = "청동사슬낫",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 1125,
                DURABILITY = 20,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 2,
                NAME_KOR = "청동사슬검",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 1950,
                DURABILITY = 29,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 105,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 3,
                NAME_KOR = "청동사슬창",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 2975,
                DURABILITY = 37,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 155,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 4,
                NAME_KOR = "강철사슬낫",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガー",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 4300,
                DURABILITY = 46,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 205,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 5,
                NAME_KOR = "강철사슬검",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 5875,
                DURABILITY = 55,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 255,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 6,
                NAME_KOR = "강철사슬창",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 7700,
                DURABILITY = 64,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 305,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 7,
                NAME_KOR = "합금사슬낫",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 9725,
                DURABILITY = 72,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 355,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 8,
                NAME_KOR = "합금사슬검",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名将の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 12050,
                DURABILITY = 81,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 405,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 9,
                NAME_KOR = "합금사슬창",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高検察庁",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 14625,
                DURABILITY = 90,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 455,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 10,
                NAME_KOR = "오리콘사슬낫",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 17450,
                DURABILITY = 99,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 505,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 11,
                NAME_KOR = "오리콘사슬검",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 20475,
                DURABILITY = 107,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 555,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 12,
                NAME_KOR = "오리콘사슬창",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 23800,
                DURABILITY = 116,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 605,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 13,
                NAME_KOR = "청동쇄겸",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖剣アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 3375,
                DURABILITY = 45,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 217,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 14,
                NAME_KOR = "강철쇄겸",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 8450,
                DURABILITY = 79,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 427,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 15,
                NAME_KOR = "합금쇄겸",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 15775,
                DURABILITY = 113,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 637,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_WEAPON05 {
                ICON = 16,
                NAME_KOR = "오리콘쇄겸",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 4,
                PRICE = 25300,
                DURABILITY = 146,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 847,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS5_HELMET05_MAX = 17;
        public struct ITEM_CLASS5_HELMET05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS5_HELMET05[] stItem_CLASS5_Helmet05 = new ITEM_CLASS5_HELMET05[ITEM_CLASS5_HELMET05_MAX] {
            new ITEM_CLASS5_HELMET05 {
                ICON = 0,
                NAME_KOR = "수련용두건",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 620,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 1,
                NAME_KOR = "낡은두건",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 880,
                DURABILITY = 14,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 4,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 2,
                NAME_KOR = "낡은머리띠",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 1455,
                DURABILITY = 17,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 3,
                NAME_KOR = "낡은복면",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 2280,
                DURABILITY = 20,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 4,
                NAME_KOR = "일반두건",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガー",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 3355,
                DURABILITY = 23,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 5,
                NAME_KOR = "일반헤어밴드",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 4680,
                DURABILITY = 26,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 6,
                NAME_KOR = "일반복면",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 6255,
                DURABILITY = 29,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 7,
                NAME_KOR = "고급두건",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 8030,
                DURABILITY = 31,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 8,
                NAME_KOR = "고급헤어밴드",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名将の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 10505,
                DURABILITY = 34,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 9,
                NAME_KOR = "고급복면",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高検察庁",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 12430,
                DURABILITY = 37,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 10,
                NAME_KOR = "희귀두건",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 15005,
                DURABILITY = 40,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 11,
                NAME_KOR = "희귀헤어밴드",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 17830,
                DURABILITY = 43,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 37,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 12,
                NAME_KOR = "희귀복면",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 13,
                NAME_KOR = "낡은서클릿",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖剣アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 2280,
                DURABILITY = 20,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 14,
                NAME_KOR = "일반서클릿",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 6305,
                DURABILITY = 30,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 15,
                NAME_KOR = "고급서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 12530,
                DURABILITY = 39,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 43,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_HELMET05 {
                ICON = 16,
                NAME_KOR = "희귀서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 4,
                PRICE = 20350,
                DURABILITY = 47,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 56,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS5_ARMOR05_MAX = 17;
        public struct ITEM_CLASS5_ARMOR05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS5_ARMOR05[] stItem_CLASS5_Armor05 = new ITEM_CLASS5_ARMOR05[ITEM_CLASS5_ARMOR05_MAX] {
            new ITEM_CLASS5_ARMOR05 {
                ICON = 0,
                NAME_KOR = "수련용호신의",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 645,
                DURABILITY = 12,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 1,
                NAME_KOR = "낡은호신의",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 995,
                DURABILITY = 15,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 2,
                NAME_KOR = "낡은닌자의",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 1620,
                DURABILITY = 18,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 3,
                NAME_KOR = "낡은제복",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 2495,
                DURABILITY = 21,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 4,
                NAME_KOR = "일반호신의",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガー",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 3620,
                DURABILITY = 24,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 5,
                NAME_KOR = "일반닌자의",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 4995,
                DURABILITY = 27,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 6,
                NAME_KOR = "일반제복",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 6620,
                DURABILITY = 30,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 7,
                NAME_KOR = "고급호신의",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 8495,
                DURABILITY = 33,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 8,
                NAME_KOR = "고급닌자의",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名将の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 10620,
                DURABILITY = 36,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 9,
                NAME_KOR = "고급제복",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高検察庁",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 12995,
                DURABILITY = 39,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 37,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 10,
                NAME_KOR = "희귀호신의",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 15619,
                DURABILITY = 42,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 41,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 11,
                NAME_KOR = "희귀닌자의",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 18445,
                DURABILITY = 44,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 12,
                NAME_KOR = "희귀제복",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 20300,
                DURABILITY = 46,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 13,
                NAME_KOR = "낡은서클릿",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖剣アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 2495,
                DURABILITY = 21,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 14,
                NAME_KOR = "일반서클릿",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 6670,
                DURABILITY = 31,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 15,
                NAME_KOR = "고급서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 13045,
                DURABILITY = 40,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 51,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_ARMOR05 {
                ICON = 16,
                NAME_KOR = "희귀서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 4,
                PRICE = 20450,
                DURABILITY = 49,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 66,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS5_GLOVES05_MAX = 17;
        public struct ITEM_CLASS5_GLOVES05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS5_GLOVES05[] stItem_CLASS5_Gloves05 = new ITEM_CLASS5_GLOVES05[ITEM_CLASS5_GLOVES05_MAX] {
            new ITEM_CLASS5_GLOVES05 {
                ICON = 0,
                NAME_KOR = "수련용반장갑",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 730,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 1,
                NAME_KOR = "낡은반장갑",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 1070,
                DURABILITY = 15,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 2,
                NAME_KOR = "낡은아대",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 1745,
                DURABILITY = 18,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 3,
                NAME_KOR = "낡은토시",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 2670,
                DURABILITY = 21,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 4,
                NAME_KOR = "일반반장갑",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガー",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 3845,
                DURABILITY = 24,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 5,
                NAME_KOR = "일반아대",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 5220,
                DURABILITY = 26,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 6,
                NAME_KOR = "일반토시",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 6895,
                DURABILITY = 29,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 18,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 7,
                NAME_KOR = "고급반장갑",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 8820,
                DURABILITY = 32,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 21,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 8,
                NAME_KOR = "고급아대",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名将の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 10995,
                DURABILITY = 35,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 9,
                NAME_KOR = "고급토시",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高検察庁",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 13420,
                DURABILITY = 38,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 27,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 10,
                NAME_KOR = "희귀반장갑",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 16094,
                DURABILITY = 41,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 11,
                NAME_KOR = "희귀아대",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 18970,
                DURABILITY = 43,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 12,
                NAME_KOR = "희귀토시",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 13,
                NAME_KOR = "낡은서클릿",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖剣アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 2670,
                DURABILITY = 21,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 14,
                NAME_KOR = "일반서클릿",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 6945,
                DURABILITY = 30,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 15,
                NAME_KOR = "고급서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 13470,
                DURABILITY = 39,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_GLOVES05 {
                ICON = 16,
                NAME_KOR = "희귀서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 4,
                PRICE = 20300,
                DURABILITY = 46,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS5_SHOES05_MAX = 17;
        public struct ITEM_CLASS5_SHOES05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS5_SHOES05[] stItem_CLASS5_Shoes05 = new ITEM_CLASS5_SHOES05[ITEM_CLASS5_SHOES05_MAX] {
            new ITEM_CLASS5_SHOES05 {
                ICON = 0,
                NAME_KOR = "수련용부츠",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "封印された大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 775,
                DURABILITY = 13,
                LIMIT_LEVEL = 5,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 1,
                NAME_KOR = "낡은롱부츠",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "亡者の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 1205,
                DURABILITY = 16,
                LIMIT_LEVEL = 9,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 2,
                NAME_KOR = "낡은레인부츠",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "復活の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 1930,
                DURABILITY = 19,
                LIMIT_LEVEL = 14,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 3,
                NAME_KOR = "낡은닌자부츠",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "マジョクジョハングンゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 2905,
                DURABILITY = 22,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 4,
                NAME_KOR = "일반롱부츠",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "大聖堂の記事ダガー",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 4080,
                DURABILITY = 24,
                LIMIT_LEVEL = 24,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 5,
                NAME_KOR = "일반레인부츠",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "貪欲のグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 5555,
                DURABILITY = 27,
                LIMIT_LEVEL = 29,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 6,
                NAME_KOR = "일반닌자부츠",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "インヨンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 7280,
                DURABILITY = 30,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 7,
                NAME_KOR = "고급롱부츠",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "ウォンジョンデウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 9255,
                DURABILITY = 33,
                LIMIT_LEVEL = 39,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 8,
                NAME_KOR = "고급레인부츠",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "名将の剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 11480,
                DURABILITY = 36,
                LIMIT_LEVEL = 44,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 9,
                NAME_KOR = "고급닌자부츠",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "オリコン最高検察庁",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 13955,
                DURABILITY = 39,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 33,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 10,
                NAME_KOR = "희귀롱부츠",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "アマンスタジアムグレートソード",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 16680,
                DURABILITY = 42,
                LIMIT_LEVEL = 54,
                EFFECT = 5,
                EFF_VALUE = 36,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 11,
                NAME_KOR = "희귀레인부츠",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "絶望の大剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 19655,
                DURABILITY = 45,
                LIMIT_LEVEL = 59,
                EFFECT = 5,
                EFF_VALUE = 39,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 12,
                NAME_KOR = "희귀닌자부츠",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "無限の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 20250,
                DURABILITY = 45,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 13,
                NAME_KOR = "낡은서클릿",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "聖剣アスカロン",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 2905,
                DURABILITY = 22,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 18,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 14,
                NAME_KOR = "일반서클릿",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "チョンサンウイゴム",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 7330,
                DURABILITY = 31,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 15,
                NAME_KOR = "고급서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 14055,
                DURABILITY = 41,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 46,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_SHOES05 {
                ICON = 16,
                NAME_KOR = "희귀서클릿",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "忍耐の両手剣",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 4,
                PRICE = 20350,
                DURABILITY = 47,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 56,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS5_AVATAR05_MAX = 3;
        public struct ITEM_CLASS5_AVATAR05 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS5_AVATAR05[] stItem_CLASS5_Avatar05 = new ITEM_CLASS5_AVATAR05[ITEM_CLASS5_AVATAR05_MAX] {
            new ITEM_CLASS5_AVATAR05 {
                ICON = 0,
                NAME_KOR = "여우 아바타",
                NAME_ENG = "Fox Avatar",
                NAME_JPN = "여우 아바타",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_AVATAR05 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS5_AVATAR05 {
                ICON = 2,
                NAME_KOR = "DLC2",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 3,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}
