// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class1 {
        public const int ITEM_CLASS1_WEAPON01_MAX = 17;
        public struct ITEM_CLASS1_WEAPON01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_WEAPON01[] stItem_CLASS1_Weapon01 = new ITEM_CLASS1_WEAPON01[ITEM_CLASS1_WEAPON01_MAX] {
            new ITEM_CLASS1_WEAPON01 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë´ë°Ë",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 700,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 1,
                NAME_KOR = "Ã»µ¿´ë°Ë",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 2200,
                DURABILITY = 19,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 2,
                NAME_KOR = "Ã»µ¿¾ç³¯°Ë",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 6350,
                DURABILITY = 27,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 95,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 3,
                NAME_KOR = "Ã»µ¿ÆÄ±«°Ë",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 13000,
                DURABILITY = 35,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 140,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 4,
                NAME_KOR = "°­Ã¶´ë°Ë",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 22200,
                DURABILITY = 44,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 185,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 5,
                NAME_KOR = "°­Ã¶¾ç³¯°Ë",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 33850,
                DURABILITY = 52,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 230,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 6,
                NAME_KOR = "°­Ã¶ÆÄ±«°Ë",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 48000,
                DURABILITY = 60,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 275,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 7,
                NAME_KOR = "ÇÕ±Ý´ë°Ë",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 64650,
                DURABILITY = 68,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 320,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 8,
                NAME_KOR = "ÇÕ±Ý¾ç³¯°Ë",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 83800,
                DURABILITY = 76,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 365,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 9,
                NAME_KOR = "ÇÕ±ÝÆÄ±«°Ë",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 105450,
                DURABILITY = 84,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 410,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 10,
                NAME_KOR = "¿À¸®ÄÜ´ë°Ë",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 129600,
                DURABILITY = 92,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 455,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 11,
                NAME_KOR = "¿À¸®ÄÜ¾ç³¯°Ë",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 156250,
                DURABILITY = 100,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 500,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 12,
                NAME_KOR = "¿À¸®ÄÜÆÄ±«°Ë",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 185450,
                DURABILITY = 109,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 545,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 13,
                NAME_KOR = "Ã»µ¿ÇÐ»ì°Ë",
                NAME_ENG = "The Lord's Greatsword",
                NAME_JPN = "ð¨èÝªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 13350,
                DURABILITY = 42,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 196,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 14,
                NAME_KOR = "°­Ã¶ÇÐ»ì°Ë",
                NAME_ENG = "Sword of the Conqueror",
                NAME_JPN = "ïÖÜ×íºªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 48700,
                DURABILITY = 74,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 385,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 15,
                NAME_KOR = "ÇÕ±ÝÇÐ»ì°Ë",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 106500,
                DURABILITY = 105,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 574,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_WEAPON01 {
                ICON = 16,
                NAME_KOR = "¿À¸®ÄÜÇÐ»ì°Ë",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 0,
                PRICE = 186800,
                DURABILITY = 136,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 763,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS1_HELMET01_MAX = 17;
        public struct ITEM_CLASS1_HELMET01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_HELMET01[] stItem_CLASS1_Helmet01 = new ITEM_CLASS1_HELMET01[ITEM_CLASS1_HELMET01_MAX] {
            new ITEM_CLASS1_HELMET01 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÅõ±¸",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 800,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 1,
                NAME_KOR = "³°ÀºÅõ±¸",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 2550,
                DURABILITY = 15,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 2,
                NAME_KOR = "³°Àº±ÙÀ§¸ð",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 6950,
                DURABILITY = 18,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 3,
                NAME_KOR = "³°ÀºÇï¸§",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 13850,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹ÝÅõ±¸",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 23300,
                DURABILITY = 25,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 30,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý±ÙÀ§¸ð",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 35200,
                DURABILITY = 28,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 37,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÇï¸§",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 49600,
                DURABILITY = 31,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 7,
                NAME_KOR = "°í±ÞÅõ±¸",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 66550,
                DURABILITY = 35,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 51,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 8,
                NAME_KOR = "°í±Þ±ÙÀ§¸ð",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 85950,
                DURABILITY = 38,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 58,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 9,
                NAME_KOR = "°í±ÞÇï¸§",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 107900,
                DURABILITY = 42,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 65,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 10,
                NAME_KOR = "Èñ±ÍÅõ±¸",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 132300,
                DURABILITY = 45,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 72,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 11,
                NAME_KOR = "Èñ±Í±ÙÀ§¸ð",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 159200,
                DURABILITY = 48,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 79,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÇï¸§",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 13,
                NAME_KOR = "³°Àº¿ëÅõ±¸",
                NAME_ENG = "The Lord's Greatsword",
                NAME_JPN = "ð¨èÝªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 13900,
                DURABILITY = 22,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý¿ëÅõ±¸",
                NAME_ENG = "Sword of the Conqueror",
                NAME_JPN = "ïÖÜ×íºªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 49750,
                DURABILITY = 34,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 62,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 15,
                NAME_KOR = "°í±Þ¿ëÅõ±¸",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 108050,
                DURABILITY = 45,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 91,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_HELMET01 {
                ICON = 16,
                NAME_KOR = "Èñ±Í¿ëÅõ±¸",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 0,
                PRICE = 182750,
                DURABILITY = 55,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 119,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS1_ARMOR01_MAX = 17;
        public struct ITEM_CLASS1_ARMOR01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_ARMOR01[] stItem_CLASS1_Armor01 = new ITEM_CLASS1_ARMOR01[ITEM_CLASS1_ARMOR01_MAX] {
            new ITEM_CLASS1_ARMOR01 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë°©¿Ê",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 1100,
                DURABILITY = 13,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 6,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 1,
                NAME_KOR = "³°Àº°©¿Ê",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 3250,
                DURABILITY = 16,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 13,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 2,
                NAME_KOR = "³°Àº¾Æ¸Ó",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 8150,
                DURABILITY = 19,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 22,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 3,
                NAME_KOR = "³°Àº¸ÞÀÏ",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 15600,
                DURABILITY = 23,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý°©¿Ê",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 25500,
                DURABILITY = 26,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý¾Æ¸Ó",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 37950,
                DURABILITY = 30,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý¸ÞÀÏ",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 52900,
                DURABILITY = 34,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 58,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 7,
                NAME_KOR = "°í±Þ°©¿Ê",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 70300,
                DURABILITY = 37,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 67,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 8,
                NAME_KOR = "°í±Þ¾Æ¸Ó",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 90250,
                DURABILITY = 41,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 76,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 9,
                NAME_KOR = "°í±Þ¸ÞÀÏ",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 112700,
                DURABILITY = 45,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 10,
                NAME_KOR = "Èñ±Í°©¿Ê",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 137600,
                DURABILITY = 48,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 94,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 11,
                NAME_KOR = "Èñ±Í¾Æ¸Ó",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 165050,
                DURABILITY = 52,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 103,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 12,
                NAME_KOR = "Èñ±Í¸ÞÀÏ",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 182700,
                DURABILITY = 54,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 109,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 13,
                NAME_KOR = "³°Àº¿ë°©",
                NAME_ENG = "The Lord's Greatsword",
                NAME_JPN = "ð¨èÝªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 15650,
                DURABILITY = 24,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý¿ë°©",
                NAME_ENG = "Sword of the Conqueror",
                NAME_JPN = "ïÖÜ×íºªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 53050,
                DURABILITY = 37,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 82,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 15,
                NAME_KOR = "°í±Þ¿ë°©",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 112900,
                DURABILITY = 49,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 119,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_ARMOR01 {
                ICON = 16,
                NAME_KOR = "Èñ±Í¿ë°©",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 0,
                PRICE = 182950,
                DURABILITY = 59,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 152,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS1_GLOVES01_MAX = 17;
        public struct ITEM_CLASS1_GLOVES01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_GLOVES01[] stItem_CLASS1_Gloves01 = new ITEM_CLASS1_GLOVES01[ITEM_CLASS1_GLOVES01_MAX] {
            new ITEM_CLASS1_GLOVES01 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ëÀå°©",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 1450,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 1,
                NAME_KOR = "³°Àº°¡Á×Àå°©",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 4000,
                DURABILITY = 16,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 2,
                NAME_KOR = "³°Àº°­Ã¶Àå°©",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 9400,
                DURABILITY = 19,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 3,
                NAME_KOR = "³°ÀºÆÇ±ÝÀå°©",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 17300,
                DURABILITY = 22,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý°¡Á×Àå°©",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 27700,
                DURABILITY = 25,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ý°­Ã¶Àå°©",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 40600,
                DURABILITY = 28,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹ÝÆÇ±ÝÀå°©",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 56000,
                DURABILITY = 31,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 7,
                NAME_KOR = "°í±Þ°¡Á×Àå°©",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 73900,
                DURABILITY = 34,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 39,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 8,
                NAME_KOR = "°í±Þ°­Ã¶Àå°©",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 94300,
                DURABILITY = 37,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 9,
                NAME_KOR = "°í±ÞÆÇ±ÝÀå°©",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 117250,
                DURABILITY = 41,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 10,
                NAME_KOR = "Èñ±Í°¡Á×Àå°©",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 142650,
                DURABILITY = 44,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 54,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 11,
                NAME_KOR = "Èñ±Í°­Ã¶Àå°©",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 170550,
                DURABILITY = 47,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 59,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 12,
                NAME_KOR = "Èñ±ÍÆÇ±ÝÀå°©",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 182400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 13,
                NAME_KOR = "³°Àº¿ëÀå°©",
                NAME_ENG = "The Lord's Greatsword",
                NAME_JPN = "ð¨èÝªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 17350,
                DURABILITY = 23,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý¿ëÀå°©",
                NAME_ENG = "Sword of the Conqueror",
                NAME_JPN = "ïÖÜ×íºªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 56100,
                DURABILITY = 33,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 15,
                NAME_KOR = "°í±Þ¿ëÀå°©",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 117350,
                DURABILITY = 43,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 68,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_GLOVES01 {
                ICON = 16,
                NAME_KOR = "Èñ±Í¿ëÀå°©",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 0,
                PRICE = 182550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 85,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS1_SHOES01_MAX = 17;
        public struct ITEM_CLASS1_SHOES01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_SHOES01[] stItem_CLASS1_Shoes01 = new ITEM_CLASS1_SHOES01[ITEM_CLASS1_SHOES01_MAX] {
            new ITEM_CLASS1_SHOES01 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë±ºÈ­",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 1450,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 1,
                NAME_KOR = "³°Àº±ºÈ­",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 4000,
                DURABILITY = 16,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 10,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 2,
                NAME_KOR = "³°ÀºÀüÅõÈ­",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 9400,
                DURABILITY = 19,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 16,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 3,
                NAME_KOR = "³°Àº´Ù¸®°©¿Ê",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 17300,
                DURABILITY = 22,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 22,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý±ºÈ­",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 27700,
                DURABILITY = 25,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÀüÅõÈ­",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 40650,
                DURABILITY = 29,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý´Ù¸®°©¿Ê",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 56050,
                DURABILITY = 32,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 40,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 7,
                NAME_KOR = "°í±Þ±ºÈ­",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 73950,
                DURABILITY = 35,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 46,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 8,
                NAME_KOR = "°í±ÞÀüÅõÈ­",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 94350,
                DURABILITY = 38,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 9,
                NAME_KOR = "°í±Þ´Ù¸®°©¿Ê",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 117300,
                DURABILITY = 42,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 58,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 10,
                NAME_KOR = "Èñ±Í±ºÈ­",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 142700,
                DURABILITY = 45,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 64,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÀüÅõÈ­",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 170600,
                DURABILITY = 48,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 70,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 12,
                NAME_KOR = "Èñ±Í´Ù¸®°©¿Ê",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 182500,
                DURABILITY = 50,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 73,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 13,
                NAME_KOR = "³°Àº±×¸®ºê",
                NAME_ENG = "The Lord's Greatsword",
                NAME_JPN = "ð¨èÝªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 17350,
                DURABILITY = 23,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý±×¸®ºê",
                NAME_ENG = "Sword of the Conqueror",
                NAME_JPN = "ïÖÜ×íºªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 56150,
                DURABILITY = 34,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 56,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 15,
                NAME_KOR = "°í±Þ±×¸®ºê",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 117450,
                DURABILITY = 45,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 82,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_SHOES01 {
                ICON = 16,
                NAME_KOR = "Èñ±Í±×¸®ºê",
                NAME_ENG = "For example, have been sealed",
                NAME_JPN = "ÜæìÔªµªìª¿ÖÇªâ",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 0,
                PRICE = 182650,
                DURABILITY = 53,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 102,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS1_AVATAR01_MAX = 3;
        public struct ITEM_CLASS1_AVATAR01 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS1_AVATAR01[] stItem_CLASS1_Avatar01 = new ITEM_CLASS1_AVATAR01[ITEM_CLASS1_AVATAR01_MAX] {
            new ITEM_CLASS1_AVATAR01 {
                ICON = 0,
                NAME_KOR = "Æë±Ï ¾Æ¹ÙÅ¸",
                NAME_ENG = "Æë±Ï ¾Æ¹ÙÅ¸",
                NAME_JPN = "Æë±Ï ¾Æ¹ÙÅ¸",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 0,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_AVATAR01 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 0,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS1_AVATAR01 {
                ICON = 2,
                NAME_KOR = "Ã»µ¿¾ç³¯°Ë",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 0,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}