// AUTO-GENERATED FILE
// Language: cpp
// Path: xldata_converter.cpp
namespace NXLData {
    class item_class3 {
        public const int ITEM_CLASS3_WEAPON03_MAX = 17;
        public struct ITEM_CLASS3_WEAPON03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_WEAPON03[] stItem_CLASS3_Weapon03 = new ITEM_CLASS3_WEAPON03[ITEM_CLASS3_WEAPON03_MAX] {
            new ITEM_CLASS3_WEAPON03 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë³ÊÅ¬",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 655,
                DURABILITY = 13,
                LIMIT_LEVEL = 1,
                EFFECT = 4,
                EFF_VALUE = 15,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 1,
                NAME_KOR = "Ã»µ¿³ÊÅ¬",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 1125,
                DURABILITY = 20,
                LIMIT_LEVEL = 5,
                EFFECT = 4,
                EFF_VALUE = 55,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 2,
                NAME_KOR = "Ã»µ¿ÇÇ½ºÆ®",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 1950,
                DURABILITY = 29,
                LIMIT_LEVEL = 10,
                EFFECT = 4,
                EFF_VALUE = 105,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 3,
                NAME_KOR = "Ã»µ¿Å¬·¯",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 2975,
                DURABILITY = 37,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 155,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 4,
                NAME_KOR = "°­Ã¶³ÊÅ¬",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 4300,
                DURABILITY = 46,
                LIMIT_LEVEL = 20,
                EFFECT = 4,
                EFF_VALUE = 205,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 5,
                NAME_KOR = "°­Ã¶ÇÇ½ºÆ®",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 5875,
                DURABILITY = 55,
                LIMIT_LEVEL = 25,
                EFFECT = 4,
                EFF_VALUE = 255,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 6,
                NAME_KOR = "°­Ã¶Å¬·¯",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 7700,
                DURABILITY = 64,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 305,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 7,
                NAME_KOR = "ÇÕ±Ý³ÊÅ¬",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 9725,
                DURABILITY = 72,
                LIMIT_LEVEL = 35,
                EFFECT = 4,
                EFF_VALUE = 355,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 8,
                NAME_KOR = "ÇÕ±ÝÇÇ½ºÆ®",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 12050,
                DURABILITY = 81,
                LIMIT_LEVEL = 40,
                EFFECT = 4,
                EFF_VALUE = 405,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 9,
                NAME_KOR = "ÇÕ±ÝÅ¬·¯",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 14625,
                DURABILITY = 90,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 455,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 10,
                NAME_KOR = "¿À¸®ÄÜ³ÊÅ¬",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 17450,
                DURABILITY = 99,
                LIMIT_LEVEL = 50,
                EFFECT = 4,
                EFF_VALUE = 505,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 11,
                NAME_KOR = "¿À¸®ÄÜÇÇ½ºÆ®",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 20475,
                DURABILITY = 107,
                LIMIT_LEVEL = 55,
                EFFECT = 4,
                EFF_VALUE = 555,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 12,
                NAME_KOR = "¿À¸®ÄÜÅ¬·¯",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 23800,
                DURABILITY = 116,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 605,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 13,
                NAME_KOR = "Ã»µ¿±Ç°©",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 3375,
                DURABILITY = 45,
                LIMIT_LEVEL = 15,
                EFFECT = 4,
                EFF_VALUE = 217,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 14,
                NAME_KOR = "°­Ã¶±Ç°©",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 8450,
                DURABILITY = 79,
                LIMIT_LEVEL = 30,
                EFFECT = 4,
                EFF_VALUE = 427,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 15,
                NAME_KOR = "ÇÕ±Ý±Ç°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 15775,
                DURABILITY = 113,
                LIMIT_LEVEL = 45,
                EFFECT = 4,
                EFF_VALUE = 637,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_WEAPON03 {
                ICON = 16,
                NAME_KOR = "¿À¸®ÄÜ±Ç°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 0,
                CHARCLASSTYPE = 2,
                PRICE = 25300,
                DURABILITY = 146,
                LIMIT_LEVEL = 60,
                EFFECT = 4,
                EFF_VALUE = 847,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS3_HELMET03_MAX = 17;
        public struct ITEM_CLASS3_HELMET03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_HELMET03[] stItem_CLASS3_Helmet03 = new ITEM_CLASS3_HELMET03[ITEM_CLASS3_HELMET03_MAX] {
            new ITEM_CLASS3_HELMET03 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë°¡Á×¸ð",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 620,
                DURABILITY = 12,
                LIMIT_LEVEL = 2,
                EFFECT = 5,
                EFF_VALUE = 3,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 1,
                NAME_KOR = "³°Àº°¡Á×¸ð",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 880,
                DURABILITY = 14,
                LIMIT_LEVEL = 6,
                EFFECT = 5,
                EFF_VALUE = 8,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 2,
                NAME_KOR = "³°ÀºÃßÀå¸ð",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 1505,
                DURABILITY = 18,
                LIMIT_LEVEL = 11,
                EFFECT = 5,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 3,
                NAME_KOR = "³°Àº±Í¸é°©",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 2330,
                DURABILITY = 21,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 20,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý°¡Á×¸ð",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 3405,
                DURABILITY = 24,
                LIMIT_LEVEL = 21,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÃßÀå¸ð",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 4730,
                DURABILITY = 27,
                LIMIT_LEVEL = 26,
                EFFECT = 5,
                EFF_VALUE = 32,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý±Í¸é°©",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 6355,
                DURABILITY = 31,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 7,
                NAME_KOR = "°í±Þ°¡Á×¸ð",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 8180,
                DURABILITY = 34,
                LIMIT_LEVEL = 36,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 8,
                NAME_KOR = "°í±ÞÃßÀå¸ð",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 10255,
                DURABILITY = 37,
                LIMIT_LEVEL = 41,
                EFFECT = 5,
                EFF_VALUE = 50,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 9,
                NAME_KOR = "°í±Þ±Í¸é°©",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 12580,
                DURABILITY = 40,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 56,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 10,
                NAME_KOR = "Èñ±Í°¡Á×¸ð",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 15205,
                DURABILITY = 44,
                LIMIT_LEVEL = 51,
                EFFECT = 5,
                EFF_VALUE = 62,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÃßÀå¸ð",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 18030,
                DURABILITY = 47,
                LIMIT_LEVEL = 56,
                EFFECT = 5,
                EFF_VALUE = 68,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 12,
                NAME_KOR = "Èñ±Í±Í¸é°©",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 20500,
                DURABILITY = 50,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 73,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 13,
                NAME_KOR = "³°Àº±Í¸é°©",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 2380,
                DURABILITY = 22,
                LIMIT_LEVEL = 16,
                EFFECT = 5,
                EFF_VALUE = 26,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý±Í¸é°©",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 6405,
                DURABILITY = 32,
                LIMIT_LEVEL = 31,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 15,
                NAME_KOR = "°í±Þ±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 12730,
                DURABILITY = 43,
                LIMIT_LEVEL = 46,
                EFFECT = 5,
                EFF_VALUE = 77,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_HELMET03 {
                ICON = 16,
                NAME_KOR = "Èñ±Í±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 1,
                CHARCLASSTYPE = 2,
                PRICE = 20650,
                DURABILITY = 53,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 100,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS3_ARMOR03_MAX = 17;
        public struct ITEM_CLASS3_ARMOR03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_ARMOR03[] stItem_CLASS3_Armor03 = new ITEM_CLASS3_ARMOR03[ITEM_CLASS3_ARMOR03_MAX] {
            new ITEM_CLASS3_ARMOR03 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë¼ö·Ãº¹",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 695,
                DURABILITY = 13,
                LIMIT_LEVEL = 3,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 1,
                NAME_KOR = "³°Àº¼ö·Ãº¹",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 995,
                DURABILITY = 15,
                LIMIT_LEVEL = 7,
                EFFECT = 5,
                EFF_VALUE = 12,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 2,
                NAME_KOR = "³°Àºµµº¹",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 1670,
                DURABILITY = 19,
                LIMIT_LEVEL = 12,
                EFFECT = 5,
                EFF_VALUE = 20,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 3,
                NAME_KOR = "³°Àº°­½Åº¹",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 2545,
                DURABILITY = 22,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 28,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý¼ö·Ãº¹",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 3720,
                DURABILITY = 26,
                LIMIT_LEVEL = 22,
                EFFECT = 5,
                EFF_VALUE = 36,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹Ýµµº¹",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 5095,
                DURABILITY = 29,
                LIMIT_LEVEL = 27,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý°­½Åº¹",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 6770,
                DURABILITY = 33,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 52,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 7,
                NAME_KOR = "°í±Þ¼ö·Ãº¹",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 8645,
                DURABILITY = 36,
                LIMIT_LEVEL = 37,
                EFFECT = 5,
                EFF_VALUE = 60,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 8,
                NAME_KOR = "°í±Þµµº¹",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 10820,
                DURABILITY = 40,
                LIMIT_LEVEL = 42,
                EFFECT = 5,
                EFF_VALUE = 68,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 9,
                NAME_KOR = "°í±Þ°­½Åº¹",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 13195,
                DURABILITY = 43,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 76,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 10,
                NAME_KOR = "Èñ±Í¼ö·Ãº¹",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 15869,
                DURABILITY = 47,
                LIMIT_LEVEL = 52,
                EFFECT = 5,
                EFF_VALUE = 84,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 11,
                NAME_KOR = "Èñ±Íµµº¹",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 18745,
                DURABILITY = 50,
                LIMIT_LEVEL = 57,
                EFFECT = 5,
                EFF_VALUE = 92,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 12,
                NAME_KOR = "Èñ±Í°­½Åº¹",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 20650,
                DURABILITY = 53,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 97,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 13,
                NAME_KOR = "³°Àº±Í¸é°©",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 2645,
                DURABILITY = 24,
                LIMIT_LEVEL = 17,
                EFFECT = 5,
                EFF_VALUE = 38,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý±Í¸é°©",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 6870,
                DURABILITY = 35,
                LIMIT_LEVEL = 32,
                EFFECT = 5,
                EFF_VALUE = 71,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 15,
                NAME_KOR = "°í±Þ±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 13395,
                DURABILITY = 47,
                LIMIT_LEVEL = 47,
                EFFECT = 5,
                EFF_VALUE = 105,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_ARMOR03 {
                ICON = 16,
                NAME_KOR = "Èñ±Í±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 2,
                CHARCLASSTYPE = 2,
                PRICE = 20850,
                DURABILITY = 57,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 134,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS3_GLOVES03_MAX = 17;
        public struct ITEM_CLASS3_GLOVES03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_GLOVES03[] stItem_CLASS3_Gloves03 = new ITEM_CLASS3_GLOVES03[ITEM_CLASS3_GLOVES03_MAX] {
            new ITEM_CLASS3_GLOVES03 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë±Û·¯ºê",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 730,
                DURABILITY = 13,
                LIMIT_LEVEL = 4,
                EFFECT = 5,
                EFF_VALUE = 5,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 1,
                NAME_KOR = "³°Àº±Û·¯ºê",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 1120,
                DURABILITY = 16,
                LIMIT_LEVEL = 8,
                EFFECT = 5,
                EFF_VALUE = 9,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 2,
                NAME_KOR = "³°ÀºÅÐÀå°©",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 1795,
                DURABILITY = 19,
                LIMIT_LEVEL = 13,
                EFFECT = 5,
                EFF_VALUE = 14,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 3,
                NAME_KOR = "³°Àº°ÇÆ²¸´",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 2720,
                DURABILITY = 22,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 19,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý±Û·¯ºê",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 3895,
                DURABILITY = 25,
                LIMIT_LEVEL = 23,
                EFFECT = 5,
                EFF_VALUE = 24,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÅÐÀå°©",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 5320,
                DURABILITY = 28,
                LIMIT_LEVEL = 28,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý°ÇÆ²¸´",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 6995,
                DURABILITY = 31,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 34,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 7,
                NAME_KOR = "°í±Þ±Û·¯ºê",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 8920,
                DURABILITY = 34,
                LIMIT_LEVEL = 38,
                EFFECT = 5,
                EFF_VALUE = 39,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 8,
                NAME_KOR = "°í±ÞÅÐÀå°©",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 11095,
                DURABILITY = 37,
                LIMIT_LEVEL = 43,
                EFFECT = 5,
                EFF_VALUE = 44,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 9,
                NAME_KOR = "°í±Þ°ÇÆ²¸´",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 13570,
                DURABILITY = 41,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 49,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 10,
                NAME_KOR = "Èñ±Í±Û·¯ºê",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 16244,
                DURABILITY = 44,
                LIMIT_LEVEL = 53,
                EFFECT = 5,
                EFF_VALUE = 54,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÅÐÀå°©",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 19170,
                DURABILITY = 47,
                LIMIT_LEVEL = 58,
                EFFECT = 5,
                EFF_VALUE = 59,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 12,
                NAME_KOR = "Èñ±Í°ÇÆ²¸´",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 20400,
                DURABILITY = 48,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 61,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 13,
                NAME_KOR = "³°Àº±Í¸é°©",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 2770,
                DURABILITY = 23,
                LIMIT_LEVEL = 18,
                EFFECT = 5,
                EFF_VALUE = 25,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý±Í¸é°©",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 7095,
                DURABILITY = 33,
                LIMIT_LEVEL = 33,
                EFFECT = 5,
                EFF_VALUE = 46,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 15,
                NAME_KOR = "°í±Þ±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 13670,
                DURABILITY = 43,
                LIMIT_LEVEL = 48,
                EFFECT = 5,
                EFF_VALUE = 67,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_GLOVES03 {
                ICON = 16,
                NAME_KOR = "Èñ±Í±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 3,
                CHARCLASSTYPE = 2,
                PRICE = 20550,
                DURABILITY = 51,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 84,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS3_SHOES03_MAX = 17;
        public struct ITEM_CLASS3_SHOES03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_SHOES03[] stItem_CLASS3_Shoes03 = new ITEM_CLASS3_SHOES03[ITEM_CLASS3_SHOES03_MAX] {
            new ITEM_CLASS3_SHOES03 {
                ICON = 0,
                NAME_KOR = "¼ö·Ã¿ë°¢¹Ý",
                NAME_ENG = "The bayonet seal",
                NAME_JPN = "ÜæìÔªµªìª¿ÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 825,
                DURABILITY = 14,
                LIMIT_LEVEL = 5,
                EFFECT = 5,
                EFF_VALUE = 7,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 1,
                NAME_KOR = "³°Àº°¢¹Ý",
                NAME_ENG = "Sword of the Dead",
                NAME_JPN = "ØÌíºªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 1205,
                DURABILITY = 16,
                LIMIT_LEVEL = 9,
                EFFECT = 5,
                EFF_VALUE = 11,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 2,
                NAME_KOR = "³°ÀºÅÐ½Å",
                NAME_ENG = "Sword of the Resurrection",
                NAME_JPN = "ÜÖüÀªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 1980,
                DURABILITY = 20,
                LIMIT_LEVEL = 14,
                EFFECT = 5,
                EFF_VALUE = 17,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 3,
                NAME_KOR = "³°Àº¿öÄ¿",
                NAME_ENG = "Majokjeohanggungeom",
                NAME_JPN = "«Þ«¸«ç«¯«¸«ç«Ï«ó«°«ó«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 2955,
                DURABILITY = 23,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 23,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 4,
                NAME_KOR = "ÀÏ¹Ý°¢¹Ý",
                NAME_ENG = "Cathedral articles dagger",
                NAME_JPN = "ÓÞá¡ÓÑªÎÑÀÞÀ«À«¬?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 4180,
                DURABILITY = 26,
                LIMIT_LEVEL = 24,
                EFFECT = 5,
                EFF_VALUE = 29,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 5,
                NAME_KOR = "ÀÏ¹ÝÅÐ½Å",
                NAME_ENG = "Sword of greed",
                NAME_JPN = "÷±é°ªÎ«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 5655,
                DURABILITY = 29,
                LIMIT_LEVEL = 29,
                EFFECT = 5,
                EFF_VALUE = 35,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 6,
                NAME_KOR = "ÀÏ¹Ý¿öÄ¿",
                NAME_ENG = "Inyeonuigeom",
                NAME_JPN = "«¤«ó«è«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 7430,
                DURABILITY = 33,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 41,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 7,
                NAME_KOR = "°í±Þ°¢¹Ý",
                NAME_ENG = "Wonjeongdaeuigeom",
                NAME_JPN = "«¦«©«ó«¸«ç«ó«Ç«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 9405,
                DURABILITY = 36,
                LIMIT_LEVEL = 39,
                EFFECT = 5,
                EFF_VALUE = 47,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 8,
                NAME_KOR = "°í±ÞÅÐ½Å",
                NAME_ENG = "Scenes of the Sword",
                NAME_JPN = "Ù£?ªÎ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 11630,
                DURABILITY = 39,
                LIMIT_LEVEL = 44,
                EFFECT = 5,
                EFF_VALUE = 53,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 9,
                NAME_KOR = "°í±Þ¿öÄ¿",
                NAME_ENG = "Oricon bayonet",
                NAME_JPN = "«ª«ê«³«óõÌÍÔ?óÌ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 14105,
                DURABILITY = 42,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 59,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 10,
                NAME_KOR = "Èñ±Í°¢¹Ý",
                NAME_ENG = "Palladium Gulf Bayonet",
                NAME_JPN = "«¢«Þ«ó«¹«¿«¸«¢«à«°«ì?«È«½?«É",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 16880,
                DURABILITY = 46,
                LIMIT_LEVEL = 54,
                EFFECT = 5,
                EFF_VALUE = 65,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 11,
                NAME_KOR = "Èñ±ÍÅÐ½Å",
                NAME_ENG = "Sword of Despair",
                NAME_JPN = "ï¾ØÐªÎÓÞ?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 19855,
                DURABILITY = 49,
                LIMIT_LEVEL = 59,
                EFFECT = 5,
                EFF_VALUE = 71,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 12,
                NAME_KOR = "Èñ±Í¿öÄ¿",
                NAME_ENG = "Infinity's Greatsword",
                NAME_JPN = "ÙíùÚªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 1,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 20500,
                DURABILITY = 50,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 73,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 13,
                NAME_KOR = "³°Àº±Í¸é°©",
                NAME_ENG = "Asda seonggeom Karon",
                NAME_JPN = "á¡?«¢«¹«««í«ó",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 3005,
                DURABILITY = 24,
                LIMIT_LEVEL = 19,
                EFFECT = 5,
                EFF_VALUE = 31,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 14,
                NAME_KOR = "ÀÏ¹Ý±Í¸é°©",
                NAME_ENG = "Cheonsanguigeom",
                NAME_JPN = "«Á«ç«ó«µ«ó«¦«¤«´«à",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 7530,
                DURABILITY = 35,
                LIMIT_LEVEL = 34,
                EFFECT = 5,
                EFF_VALUE = 57,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 15,
                NAME_KOR = "°í±Þ±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 14255,
                DURABILITY = 45,
                LIMIT_LEVEL = 49,
                EFFECT = 5,
                EFF_VALUE = 82,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_SHOES03 {
                ICON = 16,
                NAME_KOR = "Èñ±Í±Í¸é°©",
                NAME_ENG = "Greatsword of patience",
                NAME_JPN = "ìÛÒ±ªÎ?â¢?",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 1,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 4,
                CHARCLASSTYPE = 2,
                PRICE = 20650,
                DURABILITY = 53,
                LIMIT_LEVEL = 60,
                EFFECT = 5,
                EFF_VALUE = 100,
                EFF_POS = 0,
            },
        };
        public const int ITEM_CLASS3_AVATAR03_MAX = 3;
        public struct ITEM_CLASS3_AVATAR03 {
            public int ICON;
            public string	NAME_KOR; // [72*2]
            public string	NAME_ENG; // [72*2]
            public string	NAME_JPN; // [72*2]
            public int	DLC_TYPE;
            public int	USING;
            public int	DESTROY;
            public int	SALE;
            public int	ITEM_EXCHANGE;
            public int	STACK;
            public int	TYPE;
            public int	SUBTYPE;
            public int	CHARCLASSTYPE;
            public int	PRICE;
            public int	DURABILITY;
            public int	LIMIT_LEVEL;
            public int	EFFECT;
            public int	EFF_VALUE;
            public int	EFF_POS;
        }
        public static ITEM_CLASS3_AVATAR03[] stItem_CLASS3_Avatar03 = new ITEM_CLASS3_AVATAR03[ITEM_CLASS3_AVATAR03_MAX] {
            new ITEM_CLASS3_AVATAR03 {
                ICON = 0,
                NAME_KOR = "È£¶ûÀÌ ¾Æ¹ÙÅ¸",
                NAME_ENG = "È£¶ûÀÌ ¾Æ¹ÙÅ¸",
                NAME_JPN = "È£¶ûÀÌ ¾Æ¹ÙÅ¸",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 2,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 0,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_AVATAR03 {
                ICON = 1,
                NAME_KOR = "DLC1",
                NAME_ENG = "DLC1",
                NAME_JPN = "DLC1",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 2,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 1,
                EFF_POS = 0,
            },
            new ITEM_CLASS3_AVATAR03 {
                ICON = 2,
                NAME_KOR = "DLC2",
                NAME_ENG = "DLC2",
                NAME_JPN = "DLC2",
                DLC_TYPE = 0,
                USING = 0,
                DESTROY = 1,
                SALE = 0,
                ITEM_EXCHANGE = 0,
                STACK = 0,
                TYPE = 0,
                SUBTYPE = 5,
                CHARCLASSTYPE = 2,
                PRICE = 0,
                DURABILITY = 0,
                LIMIT_LEVEL = 1,
                EFFECT = -1,
                EFF_VALUE = 2,
                EFF_POS = 0,
            },
        };
    }
}