#ifndef __ENUM_H__
#define __ENUM_H__

enum INVEN_BAG_TYPE {
    BAG_TYPE_NORMAL = 0,
    BAG_TYPE_ACCESSORY,
    BAG_TYPE_MISC,
    BAG_TYPE_TITLE,
    BAG_TYPE_WAREHOUSE,
    BAG_TYPE_FAIRY,
    BAG_TYPE_BATTLE_PET,
    BAG_TYPE_MAX
};

enum EnumItemEquipPosition {
	ITEM_EQUIP_POS_NONE = -1,
	/// ?û•Îπ?
	ITEM_EQUIP_POS_WEAPON = 0,					/// Î¨¥Í∏∞		: ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå, ÏΩîÏä§?ä¨, ?Ñ∏?ä∏
	ITEM_EQUIP_POS_HELMET,		//1				/// ?à¨Íµ?		: ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå, ÏΩîÏä§?ä¨, ?Ñ∏?ä∏
	ITEM_EQUIP_POS_ARMOR,		//2				/// Í∞ëÏò∑		: ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå, ÏΩîÏä§?ä¨, ?Ñ∏?ä∏
	ITEM_EQUIP_POS_GLOVE,		//3				/// ?û•Í∞?		: ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå
	ITEM_EQUIP_POS_SHOES,		//4				/// ?ã†Î∞?		: ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå
	ITEM_EQUIP_POS_AVARTAR,		//5				/// ?ïÑÎ∞îÌ??

	/// ?û•?ã†Íµ?(?Ç¥Íµ¨ÎèÑ Í∞êÏÜå ?óÜ?ùå, ?àòÎ¶¨Î∂à?ïÑ?öî)
	ITEM_EQUIP_POS_NECKLACE,	//6				/// Î™©Í±∏?ù¥		: ?ó¨Í∏∞Î???Ñ∞ ?àòÎ¶¨Î∂àÍ∞?, ?Ç¥Íµ¨ÎèÑ Í∞êÏÜå ?óÜ?ùå(?àòÎ¶¨Î∂à?ïÑ?öî)
	ITEM_EQUIP_POS_CLOAK,		//7				/// ÎßùÌÜ†
	ITEM_EQUIP_POS_RING,		//8				/// Î∞òÏ??
	ITEM_EQUIP_POS_CHARM,		//9				/// Î∂??†Å
	ITEM_EQUIP_POS_VEHICLE,		//10			/// ?ÉàÍ≤?
	ITEM_EQUIP_POS_TITLE,		//11			/// Ïπ??ò∏
	MAX_ITEM_EQUIP_STAT,		//12			/// ?ã§?†ú ?ïÑ?ù¥?Öú ?ä•?†•Ïπ? ?†Å?ö©?ï† ?úÑÏπ?
	ITEM_EQUIP_POS_FAIRY = MAX_ITEM_EQUIP_STAT,	//12		/// ?éò?ñ¥Î¶?
	ITEM_EQUIP_POS_PET,			//13			/// ?†Ñ?à¨?é´
	MAX_ITEM_EQUIP_POS,

	// ?û°?ôî, ?û¨Î£?
	ITEM_SUBTYPE_FAIRY_EGG = MAX_ITEM_EQUIP_POS,
	ITEM_SUBTYPE_PET_EGG,
	ITEM_SUBTYPE_POTION,
	ITEM_SUBTYPE_FOOD,
	ITEM_SUBTYPE_MATERIAL_ITEM,
	ITEM_SUBTYPE_PORTAL,
	ITEM_SUBTYPE_REPAIR,
	ITEM_SUBTYPE_MATERIAL,
	ITEM_SUBTYPE_SALE_MIX_SCROLL,
	ITEM_SUBTYPE_REBIRTH,
	ITEM_SUBTYPE_IDENTIFY,
	ITEM_SUBTYPE_MAX_DURABILITY,
	ITEM_SUBTYPE_UPGRADE_STONE,
	ITEM_SUBTYPE_RETURN_STATPOINT,
	ITEM_SUBTYPE_RETURN_SKILLPOINT,
	ITEM_SUBTYPE_LIGHT,
	ITEM_SUBTYPE_DROPEXP,		// 30
	ITEM_SUBTYPE_SPECIAL_POSION,
	ITEM_SUBTYPE_PORTAL_BOTH,
	ITEM_SUBTYPE_RECOVERY_ITEM,
	ITEM_SUBTYPE_MIX_BOOK,
	ITEM_SUBTYPE_KEY,
	ITEM_SUBTYPE_QUEST,
	ITEM_SUBTYPE_COLLECTION_EQUIP,
	ITEM_SUBTYPE_SET_ITEM_BOX,
	ITEM_SUBTYPE_SKILL_JAM,
	ITEM_SUBTYPE_AUTO_ROUTING,	// 40
	ITEM_SUBTYPE_BAG,
	ITEM_SUBTYPE_HELP_STONE,
	ITEM_SUBTYPE_GAMBLE_STONE,
	ITEM_SUBTYPE_TREASURE_BOX,
	ITEM_SUBTYPE_PACKAGE,
	ITEM_SUBTYPE_BLACKSMITH_KIT,
	ITEM_SUBTYPE_CHANGE_INTO_ZEN,
	ITEM_SUBTYPE_CHANGE_INTO_GOLD,
	ITEM_SUBTYPE_GOLDEN_UPGRADE_STONE,
	ITEM_SUBTYPE_ADD_BANKSLOT,	// 50
	ITEM_SUBTYPE_TICKET,
	ITEM_SUBTYPE_DUE_DATE_TICKET,
	ITEM_SUBTYPE_NO_CONDITION,
	ITEM_SUBTYPE_SETBOX_RED,
	ITEM_SUBTYPE_UPGRADE_REFINE_STEP_MAX,
	ITEM_SUBTYPE_HIGH_QULITY_UPGRADE_STONE,
	ITEM_SUBTYPE_SEAL,
	ITEM_SUBTYPE_UPGRADE,
	ITEM_SUBTYPE_GOLD,
	ITEM_SUBTYPE_EV_POINT,		// 60
	ITEM_SUBTYPE_ITEM_GACHYA_TICKET,
	ITEM_EQUIP_POS_NAME_TAG,				/// ?ù¥Î¶ÑÌëú
	ITEM_EQUIP_POS_NAME_TAG_WORLDBOSS,				/// Î≥¥ÏÉÅ?ö© ?ù¥Î¶ÑÌëú..
};

enum ContentsOpen {
	VIP_SYSTEM = 0,
};


#endif // __ENUM_H__